In [12]:
# Faten TINZAGHTI

# Extraction des séries GEO liées au récepteur androgène (AR) et aux expériences ChIP-seq

Ce script automatise l’extraction de métadonnées d’expériences ChIP-seq liées à AR déposées dans la base GEO du NCBI via les API ENTREZ.
L’API ENTREZ est un ensemble d’interfaces permettant d’interroger automatiquement les bases de données du NCBI, comme GEO ou PubMed, à l’aide de requêtes HTTP structurées.

Il effectue les étapes suivantes :

- Recherche des séries GEO correspondant au terme défini (ChIP-seq AND AR) grâce à l’API esearch.

- Récupération des métadonnées détaillées pour chaque série (identifiant GSE, titre, plateforme, nombre d’échantillons) via l’API esummary.

- Filtrage automatique des entrées incomplètes afin de ne conserver que les séries exploitables.

- Respect des limites d’accès NCBI grâce à une pause de 0,34 s entre chaque requête.

- Construction d’un tableau final avec pandas puis export en fichier CSV (GEO_AR_ChIPseq_results.csv).

In [13]:
import requests               # Pour envoyer des requêtes HTTP vers les API NCBI
from bs4 import BeautifulSoup # Pour analyser les réponses XML d'ENTREZ
import pandas as pd           # Pour construire et sauvegarder le tableau final
import time                   # Pour respecter le délai entre les requêtes NCBI

# Paramètres : termes de recherche + email obligatoire pour ENTREZ

TERM = "ChIP-seq AND AR"  # Mot-clé de recherche sur GEO (CDH2 ChIP-seq)
EMAIL = "your_email@example.com"         # Peut rester comme ça, c'est accepté par NCBI

# URL de base pour toutes les API ENTREZ
API = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"


#  Fonction : recherche des séries GEO correspondant au terme donné

def entrez_search(term):
    """
    Recherche dans la base GEO (GDS) toutes les séries liées au terme demandé.
    Retourne une liste d'identifiants internes GDS.
    """

    url = API + "esearch.fcgi"  # API "esearch" pour interroger la base de données
    params = {
        "db": "gds",            # Base GEO DataSets
        "term": term,           # Terme de recherche
        "retmax": 5000,         # Nombre max d'entrées à renvoyer
        "retmode": "xml",       # Format de retour
        "email": EMAIL          # Email exigé par NCBI (mais pas vérifié)
    }

    r = requests.get(url, params=params)      # Envoi de la requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Analyse XML de la réponse

    # On extrait toutes les balises <Id> (identifiants internes GEO)
    ids = [id_tag.text for id_tag in soup.find_all("Id")]

    return ids  # Liste d'identifiants GDS bruts


# Fonction : récupération des informations détaillées d’un GSE

def fetch_gse_metadata(gds_id):
    """
    Récupère les métadonnées d'une série GEO via l'API esummary.
    Retourne un dictionnaire {GSE, Title, Platform, Samples}.
    Ignore les entrées incomplètes.
    """

    url = API + "esummary.fcgi"  # API "esummary" pour récupérer les infos détaillées
    params = {
        "db": "gds",             # Même base : GEO DataSets
        "id": gds_id,            # Identifiant GDS trouvé dans esearch
        "retmode": "xml",
        "email": EMAIL
    }

    r = requests.get(url, params=params)      # Requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Parsing XML

    item = soup.find("DocSum")                # Bloc principal des infos
    if item is None:
        return None  # Si vide → entrée invalidée

    # Petite fonction interne qui vérifie qu’un champ existe avant de l’extraire
    def safe_find(name):
        tag = item.find("Item", {"Name": name})
        return tag.text if tag else None

    # Extraction de l'identifiant GSE réel (ex: "GSE12345")
    acc = safe_find("Accession")
    if acc is None:
        return None  # Entrée corrompue → on ignore

    # Retour d’un dictionnaire structuré (sera ajouté au CSV)
    return {
        "GSE": acc,                     # Accession GSE
        "Title": safe_find("title"),    # Titre de l'étude
        "Platform": safe_find("platform"),  # Technologie (ex: Illumina)
        "Samples": safe_find("n_samples")   # Nombre d’échantillons
    }

# Programme principal : recherche + récupération + export CS

print("Recherche des séries via ENTREZ...")
ids = entrez_search(TERM)  # On lance la recherche de tous les GDS pertinents
print(f" {len(ids)} séries trouvées via ENTREZ.\n")

results = []  # Liste pour stocker les séries valides

# Boucle sur toutes les séries trouvées
for i, gds_id in enumerate(ids):
    print(f" Lecture série {i+1}/{len(ids)} : ID {gds_id} ...")

    data = fetch_gse_metadata(gds_id)  # Récupération des métadonnées
    if data is None:
        print("  Série ignorée (métadonnées incomplètes)")  # Problème → on saute
        continue

    results.append(data)  # Ajout à la liste des résultats valides

    time.sleep(0.34)  # Pause obligatoire pour respecter la limite NCBI (3 requêtes/sec)

# Export des résultat
print("\n----------------------------------")
print(f" Séries valides : {len(results)}")
print("----------------------------------")

df = pd.DataFrame(results)                      # Conversion en tableau pandas
df.to_csv("GEO_AR_ChIPseq_results.csv", index=False)  # Sauvegarde en CSV

print("Extraction terminée.")
print("Résultats enregistrés dans : GEO_AR_ChIPseq_results.csv")

Recherche des séries via ENTREZ...
 736 séries trouvées via ENTREZ.

 Lecture série 1/736 : ID 200315393 ...
 Lecture série 2/736 : ID 200329198 ...
 Lecture série 3/736 : ID 200305396 ...
 Lecture série 4/736 : ID 200305395 ...
 Lecture série 5/736 : ID 200305394 ...
 Lecture série 6/736 : ID 200305225 ...
 Lecture série 7/736 : ID 200296178 ...
 Lecture série 8/736 : ID 200289313 ...
 Lecture série 9/736 : ID 200315959 ...
 Lecture série 10/736 : ID 200241255 ...
 Lecture série 11/736 : ID 200301368 ...
 Lecture série 12/736 : ID 200301366 ...
 Lecture série 13/736 : ID 200261412 ...
 Lecture série 14/736 : ID 200318340 ...
 Lecture série 15/736 : ID 200227688 ...
 Lecture série 16/736 : ID 200306114 ...
 Lecture série 17/736 : ID 200292273 ...
 Lecture série 18/736 : ID 200313838 ...
 Lecture série 19/736 : ID 200295408 ...
 Lecture série 20/736 : ID 200308945 ...
 Lecture série 21/736 : ID 200296270 ...
 Lecture série 22/736 : ID 200293202 ...
 Lecture série 23/736 : ID 200293101 ...
 Lecture série 24/736 : ID 200293089 ...
 Lecture série 25/736 : ID 200293080 ...
 Lecture série 26/736 : ID 200228743 ...
 Lecture série 27/736 : ID 200287905 ...
 Lecture série 28/736 : ID 200287902 ...
 Lecture série 29/736 : ID 200287901 ...
 Lecture série 30/736 : ID 200287918 ...
 Lecture série 31/736 : ID 200247347 ...
 Lecture série 32/736 : ID 200295844 ...
 Lecture série 33/736 : ID 200297048 ...
 Lecture série 34/736 : ID 200296236 ...
 Lecture série 35/736 : ID 200307813 ...
 Lecture série 36/736 : ID 200299760 ...
 Lecture série 37/736 : ID 200287088 ...
 Lecture série 38/736 : ID 200281784 ...
 Lecture série 39/736 : ID 200304127 ...
 Lecture série 40/736 : ID 200289031 ...
 Lecture série 41/736 : ID 200303171 ...
 Lecture série 42/736 : ID 200290863 ...
 Lecture série 43/736 : ID 200282406 ...
 Lecture série 44/736 : ID 200280834 ...
 Lecture série 45/736 : ID 200255132 ...
 Lecture série 46/736 : ID 200292612 ...
 Lecture série 47/736 : ID 200284519 ...
 Lecture série 48/736 : ID 200239270 ...
 Lecture série 49/736 : ID 200266213 ...
 Lecture série 50/736 : ID 200296569 ...
 Lecture série 51/736 : ID 200276050 ...
 Lecture série 52/736 : ID 200285790 ...
 Lecture série 53/736 : ID 200280803 ...
 Lecture série 54/736 : ID 200252883 ...
 Lecture série 55/736 : ID 200251978 ...
 Lecture série 56/736 : ID 200251977 ...
 Lecture série 57/736 : ID 200277606 ...
 Lecture série 58/736 : ID 200252897 ...
 Lecture série 59/736 : ID 200252841 ...
 Lecture série 60/736 : ID 200249437 ...
 Lecture série 61/736 : ID 200249435 ...
 Lecture série 62/736 : ID 200249887 ...
 Lecture série 63/736 : ID 200186873 ...
 Lecture série 64/736 : ID 200274717 ...
 Lecture série 65/736 : ID 200251895 ...
 Lecture série 66/736 : ID 200251894 ...
 Lecture série 67/736 : ID 200260726 ...
 Lecture série 68/736 : ID 200275777 ...
 Lecture série 69/736 : ID 200241290 ...
 Lecture série 70/736 : ID 200184311 ...
 Lecture série 71/736 : ID 200230508 ...
 Lecture série 72/736 : ID 200273342 ...
 Lecture série 73/736 : ID 200230507 ...
 Lecture série 74/736 : ID 200238113 ...
 Lecture série 75/736 : ID 200268252 ...
 Lecture série 76/736 : ID 200268124 ...
 Lecture série 77/736 : ID 200262744 ...
 Lecture série 78/736 : ID 200211138 ...
 Lecture série 79/736 : ID 200221140 ...
 Lecture série 80/736 : ID 200238209 ...
 Lecture série 81/736 : ID 200245749 ...
 Lecture série 82/736 : ID 200232553 ...
 Lecture série 83/736 : ID 200232552 ...
 Lecture série 84/736 : ID 200230600 ...
 Lecture série 85/736 : ID 200256129 ...
 Lecture série 86/736 : ID 200221263 ...
 Lecture série 87/736 : ID 200236860 ...
 Lecture série 88/736 : ID 200242734 ...
 Lecture série 89/736 : ID 200235956 ...
 Lecture série 90/736 : ID 200261446 ...
 Lecture série 91/736 : ID 200245967 ...
 Lecture série 92/736 : ID 200240679 ...
 Lecture série 93/736 : ID 200255308 ...
 Lecture série 94/736 : ID 200240055 ...
 Lecture série 95/736 : ID 200252635 ...
 Lecture série 96/736 : ID 200249686 ...
 Lecture série 97/736 : ID 200249685 ...
 Lecture série 98/736 : ID 200207472 ...
 Lecture série 99/736 : ID 200207230 ...
 Lecture série 100/736 : ID 200190956 ...
 Lecture série 101/736 : ID 200178254 ...
 Lecture série 102/736 : ID 200178253 ...
 Lecture série 103/736 : ID 200178248 ...
 Lecture série 104/736 : ID 200218204 ...
 Lecture série 105/736 : ID 200214754 ...
 Lecture série 106/736 : ID 200230741 ...
 Lecture série 107/736 : ID 200230740 ...
 Lecture série 108/736 : ID 200230529 ...
 Lecture série 109/736 : ID 200215161 ...
 Lecture série 110/736 : ID 200225196 ...
 Lecture série 111/736 : ID 200224687 ...
 Lecture série 112/736 : ID 200218092 ...
 Lecture série 113/736 : ID 200232690 ...
 Lecture série 114/736 : ID 200224422 ...
 Lecture série 115/736 : ID 200224421 ...
 Lecture série 116/736 : ID 200192562 ...
 Lecture série 117/736 : ID 200192555 ...
 Lecture série 118/736 : ID 200236287 ...
 Lecture série 119/736 : ID 200231748 ...
 Lecture série 120/736 : ID 200205980 ...
 Lecture série 121/736 : ID 200213664 ...
 Lecture série 122/736 : ID 200234134 ...
 Lecture série 123/736 : ID 200228895 ...
 Lecture série 124/736 : ID 200216373 ...
 Lecture série 125/736 : ID 200221613 ...
 Lecture série 126/736 : ID 200223406 ...
 Lecture série 127/736 : ID 200221826 ...
 Lecture série 128/736 : ID 200211945 ...
 Lecture série 129/736 : ID 200211944 ...
 Lecture série 130/736 : ID 200200300 ...
 Lecture série 131/736 : ID 200211639 ...
 Lecture série 132/736 : ID 200148954 ...
 Lecture série 133/736 : ID 200169129 ...
 Lecture série 134/736 : ID 200209047 ...
 Lecture série 135/736 : ID 200164968 ...
 Lecture série 136/736 : ID 200197781 ...
 Lecture série 137/736 : ID 200197780 ...
 Lecture série 138/736 : ID 200197776 ...
 Lecture série 139/736 : ID 200197774 ...
 Lecture série 140/736 : ID 200132073 ...
 Lecture série 141/736 : ID 200203036 ...
 Lecture série 142/736 : ID 200174109 ...
 Lecture série 143/736 : ID 200193073 ...
 Lecture série 144/736 : ID 200188173 ...
 Lecture série 145/736 : ID 200163220 ...
 Lecture série 146/736 : ID 200171511 ...
 Lecture série 147/736 : ID 200153583 ...
 Lecture série 148/736 : ID 200183200 ...
 Lecture série 149/736 : ID 200183198 ...
 Lecture série 150/736 : ID 200163316 ...
 Lecture série 151/736 : ID 200163145 ...
 Lecture série 152/736 : ID 200163143 ...
 Lecture série 153/736 : ID 200198916 ...
 Lecture série 154/736 : ID 200179684 ...
 Lecture série 155/736 : ID 200188150 ...
 Lecture série 156/736 : ID 200153661 ...
 Lecture série 157/736 : ID 200162293 ...
 Lecture série 158/736 : ID 200157862 ...
 Lecture série 159/736 : ID 200181224 ...
 Lecture série 160/736 : ID 200157107 ...
 Lecture série 161/736 : ID 200157104 ...
 Lecture série 162/736 : ID 200171592 ...
 Lecture série 163/736 : ID 200171589 ...
 Lecture série 164/736 : ID 200148807 ...
 Lecture série 165/736 : ID 200145333 ...
 Lecture série 166/736 : ID 200145196 ...
 Lecture série 167/736 : ID 200169073 ...
 Lecture série 168/736 : ID 200138460 ...
 Lecture série 169/736 : ID 200147875 ...
 Lecture série 170/736 : ID 200136016 ...
 Lecture série 171/736 : ID 200158279 ...
 Lecture série 172/736 : ID 200155803 ...
 Lecture série 173/736 : ID 200146886 ...
 Lecture série 174/736 : ID 200154191 ...
 Lecture série 175/736 : ID 200148935 ...
 Lecture série 176/736 : ID 200168651 ...
 Lecture série 177/736 : ID 200164543 ...
 Lecture série 178/736 : ID 200151424 ...
 Lecture série 179/736 : ID 200171005 ...
 Lecture série 180/736 : ID 200147939 ...
 Lecture série 181/736 : ID 200147938 ...
 Lecture série 182/736 : ID 200151619 ...
 Lecture série 183/736 : ID 200161189 ...
 Lecture série 184/736 : ID 200166192 ...
 Lecture série 185/736 : ID 200161167 ...
 Lecture série 186/736 : ID 200156280 ...
 Lecture série 187/736 : ID 200141582 ...
 Lecture série 188/736 : ID 200141394 ...
 Lecture série 189/736 : ID 200129930 ...
 Lecture série 190/736 : ID 200129929 ...
 Lecture série 191/736 : ID 200123767 ...
 Lecture série 192/736 : ID 200123764 ...
 Lecture série 193/736 : ID 200163623 ...
 Lecture série 194/736 : ID 200162319 ...
 Lecture série 195/736 : ID 200144960 ...
 Lecture série 196/736 : ID 200149439 ...
 Lecture série 197/736 : ID 200122922 ...
 Lecture série 198/736 : ID 200156882 ...
 Lecture série 199/736 : ID 200136129 ...
 Lecture série 200/736 : ID 200136128 ...
 Lecture série 201/736 : ID 200140017 ...
 Lecture série 202/736 : ID 200140016 ...
 Lecture série 203/736 : ID 200130408 ...
 Lecture série 204/736 : ID 200106665 ...
 Lecture série 205/736 : ID 200106660 ...
 Lecture série 206/736 : ID 200083650 ...
 Lecture série 207/736 : ID 200149007 ...
 Lecture série 208/736 : ID 200148358 ...
 Lecture série 209/736 : ID 200129951 ...
 Lecture série 210/736 : ID 200118247 ...
 Lecture série 211/736 : ID 200122572 ...
 Lecture série 212/736 : ID 200119432 ...
 Lecture série 213/736 : ID 200121880 ...
 Lecture série 214/736 : ID 200137527 ...
 Lecture série 215/736 : ID 200128883 ...
 Lecture série 216/736 : ID 200133387 ...
 Lecture série 217/736 : ID 200133386 ...
 Lecture série 218/736 : ID 200138168 ...
 Lecture série 219/736 : ID 200114267 ...
 Lecture série 220/736 : ID 200114266 ...
 Lecture série 221/736 : ID 200128018 ...
 Lecture série 222/736 : ID 200123090 ...
 Lecture série 223/736 : ID 200123089 ...
 Lecture série 224/736 : ID 200117304 ...
 Lecture série 225/736 : ID 200125245 ...
 Lecture série 226/736 : ID 200117430 ...
 Lecture série 227/736 : ID 200116397 ...
 Lecture série 228/736 : ID 200125882 ...
 Lecture série 229/736 : ID 200117534 ...
 Lecture série 230/736 : ID 200114274 ...
 Lecture série 231/736 : ID 200131381 ...
 Lecture série 232/736 : ID 200114732 ...
 Lecture série 233/736 : ID 200109748 ...
 Lecture série 234/736 : ID 200118845 ...
 Lecture série 235/736 : ID 200123565 ...
 Lecture série 236/736 : ID 200112414 ...
 Lecture série 237/736 : ID 200098069 ...
 Lecture série 238/736 : ID 200116855 ...
 Lecture série 239/736 : ID 200106305 ...
 Lecture série 240/736 : ID 200126852 ...
 Lecture série 241/736 : ID 200125552 ...
 Lecture série 242/736 : ID 200121152 ...
 Lecture série 243/736 : ID 200121151 ...
 Lecture série 244/736 : ID 200122639 ...
 Lecture série 245/736 : ID 200108704 ...
 Lecture série 246/736 : ID 200114737 ...
 Lecture série 247/736 : ID 200123618 ...
 Lecture série 248/736 : ID 200107780 ...
 Lecture série 249/736 : ID 200106559 ...
 Lecture série 250/736 : ID 200097551 ...
 Lecture série 251/736 : ID 200108144 ...
 Lecture série 252/736 : ID 200120741 ...
 Lecture série 253/736 : ID 200120738 ...
 Lecture série 254/736 : ID 200094013 ...
 Lecture série 255/736 : ID 200101765 ...
 Lecture série 256/736 : ID 200116191 ...
 Lecture série 257/736 : ID 200116189 ...
 Lecture série 258/736 : ID 200107320 ...
 Lecture série 259/736 : ID 200109062 ...
 Lecture série 260/736 : ID 200109061 ...
 Lecture série 261/736 : ID 200110657 ...
 Lecture série 262/736 : ID 200110655 ...
 Lecture série 263/736 : ID 200117179 ...
 Lecture série 264/736 : ID 200117110 ...
 Lecture série 265/736 : ID 200117104 ...
 Lecture série 266/736 : ID 200117103 ...
 Lecture série 267/736 : ID 200117102 ...
 Lecture série 268/736 : ID 200117098 ...
 Lecture série 269/736 : ID 200103871 ...
 Lecture série 270/736 : ID 200080742 ...
 Lecture série 271/736 : ID 200096084 ...
 Lecture série 272/736 : ID 200097831 ...
 Lecture série 273/736 : ID 200104399 ...
 Lecture série 274/736 : ID 200109021 ...
 Lecture série 275/736 : ID 200100710 ...
 Lecture série 276/736 : ID 200099626 ...
 Lecture série 277/736 : ID 200103449 ...
 Lecture série 278/736 : ID 200094682 ...
 Lecture série 279/736 : ID 200076336 ...
 Lecture série 280/736 : ID 200076335 ...
 Lecture série 281/736 : ID 200076334 ...
 Lecture série 282/736 : ID 200080238 ...
 Lecture série 283/736 : ID 200089938 ...
 Lecture série 284/736 : ID 200102164 ...
 Lecture série 285/736 : ID 200096652 ...
 Lecture série 286/736 : ID 200093845 ...
 Lecture série 287/736 : ID 200098809 ...
 Lecture série 288/736 : ID 200098808 ...
 Lecture série 289/736 : ID 200083653 ...
 Lecture série 290/736 : ID 200083652 ...
 Lecture série 291/736 : ID 200083651 ...
 Lecture série 292/736 : ID 200083649 ...
 Lecture série 293/736 : ID 200073994 ...
 Lecture série 294/736 : ID 200080256 ...
 Lecture série 295/736 : ID 200079358 ...
 Lecture série 296/736 : ID 200079357 ...
 Lecture série 297/736 : ID 200081859 ...
 Lecture série 298/736 : ID 200092574 ...
 Lecture série 299/736 : ID 200092347 ...
 Lecture série 300/736 : ID 200074799 ...
 Lecture série 301/736 : ID 200074798 ...
 Lecture série 302/736 : ID 200084432 ...
 Lecture série 303/736 : ID 200083860 ...
 Lecture série 304/736 : ID 200082203 ...
 Lecture série 305/736 : ID 200082202 ...
 Lecture série 306/736 : ID 200086532 ...
 Lecture série 307/736 : ID 200079601 ...
 Lecture série 308/736 : ID 200070163 ...
 Lecture série 309/736 : ID 200070161 ...
 Lecture série 310/736 : ID 200077762 ...
 Lecture série 311/736 : ID 200079128 ...
 Lecture série 312/736 : ID 200072534 ...
 Lecture série 313/736 : ID 200072714 ...
 Lecture série 314/736 : ID 200071704 ...
 Lecture série 315/736 : ID 200065066 ...
 Lecture série 316/736 : ID 200055031 ...
 Lecture série 317/736 : ID 200069043 ...
 Lecture série 318/736 : ID 200076141 ...
 Lecture série 319/736 : ID 200064528 ...
 Lecture série 320/736 : ID 200074069 ...
 Lecture série 321/736 : ID 200070079 ...
 Lecture série 322/736 : ID 200063693 ...
 Lecture série 323/736 : ID 200056288 ...
 Lecture série 324/736 : ID 200062645 ...
 Lecture série 325/736 : ID 200062442 ...
 Lecture série 326/736 : ID 200061270 ...
 Lecture série 327/736 : ID 200061268 ...
 Lecture série 328/736 : ID 200065478 ...
 Lecture série 329/736 : ID 200064657 ...
 Lecture série 330/736 : ID 200064656 ...
 Lecture série 331/736 : ID 200070679 ...
 Lecture série 332/736 : ID 200067776 ...
 Lecture série 333/736 : ID 200061394 ...
 Lecture série 334/736 : ID 200064709 ...
 Lecture série 335/736 : ID 200061838 ...
 Lecture série 336/736 : ID 200060841 ...
 Lecture série 337/736 : ID 200062492 ...
 Lecture série 338/736 : ID 200063202 ...
 Lecture série 339/736 : ID 200056086 ...
 Lecture série 340/736 : ID 200043785 ...
 Lecture série 341/736 : ID 200043720 ...
 Lecture série 342/736 : ID 200043985 ...
 Lecture série 343/736 : ID 200051334 ...
 Lecture série 344/736 : ID 200058428 ...
 Lecture série 345/736 : ID 200058478 ...
 Lecture série 346/736 : ID 200054137 ...
 Lecture série 347/736 : ID 200054110 ...
 Lecture série 348/736 : ID 200054109 ...
 Lecture série 349/736 : ID 200054104 ...
 Lecture série 350/736 : ID 200055903 ...
 Lecture série 351/736 : ID 200055901 ...
 Lecture série 352/736 : ID 200055279 ...
 Lecture série 353/736 : ID 200055007 ...
 Lecture série 354/736 : ID 200047987 ...
 Lecture série 355/736 : ID 200037345 ...
 Lecture série 356/736 : ID 200049091 ...
 Lecture série 357/736 : ID 200055064 ...
 Lecture série 358/736 : ID 200055062 ...
 Lecture série 359/736 : ID 200037617 ...
 Lecture série 360/736 : ID 200036614 ...
 Lecture série 361/736 : ID 200051621 ...
 Lecture série 362/736 : ID 200052725 ...
 Lecture série 363/736 : ID 200051106 ...
 Lecture série 364/736 : ID 200047192 ...
 Lecture série 365/736 : ID 200047181 ...
 Lecture série 366/736 : ID 200045124 ...
 Lecture série 367/736 : ID 200032892 ...
 Lecture série 368/736 : ID 200050261 ...
 Lecture série 369/736 : ID 200049402 ...
 Lecture série 370/736 : ID 200049847 ...
 Lecture série 371/736 : ID 200049201 ...
 Lecture série 372/736 : ID 200048308 ...
 Lecture série 373/736 : ID 200047120 ...
 Lecture série 374/736 : ID 200047119 ...
 Lecture série 375/736 : ID 200047220 ...
 Lecture série 376/736 : ID 200045281 ...
 Lecture série 377/736 : ID 200045203 ...
 Lecture série 378/736 : ID 200045201 ...
 Lecture série 379/736 : ID 200039880 ...
 Lecture série 380/736 : ID 200039879 ...
 Lecture série 381/736 : ID 200039654 ...
 Lecture série 382/736 : ID 200028219 ...
 Lecture série 383/736 : ID 200040050 ...
 Lecture série 384/736 : ID 200034780 ...
 Lecture série 385/736 : ID 200028950 ...
 Lecture série 386/736 : ID 200028857 ...
 Lecture série 387/736 : ID 200036030 ...
 Lecture série 388/736 : ID 200028596 ...
 Lecture série 389/736 : ID 200028264 ...
 Lecture série 390/736 : ID 200032465 ...
 Lecture série 391/736 : ID 200030624 ...
 Lecture série 392/736 : ID 200030623 ...
 Lecture série 393/736 : ID 200030622 ...
 Lecture série 394/736 : ID 200031477 ...
 Lecture série 395/736 : ID 200028789 ...
 Lecture série 396/736 : ID 200028788 ...
 Lecture série 397/736 : ID 200027724 ...
 Lecture série 398/736 : ID 200027823 ...
 Lecture série 399/736 : ID 200027682 ...
 Lecture série 400/736 : ID 200028757 ...
 Lecture série 401/736 : ID 200028292 ...
 Lecture série 402/736 : ID 200023537 ...
 Lecture série 403/736 : ID 200023149 ...
 Lecture série 404/736 : ID 200014092 ...
 Lecture série 405/736 : ID 200014028 ...
 Lecture série 406/736 : ID 200020042 ...
 Lecture série 407/736 : ID 308966503 ...
 Lecture série 408/736 : ID 308966502 ...
 Lecture série 409/736 : ID 309144141 ...
 Lecture série 410/736 : ID 309035774 ...
 Lecture série 411/736 : ID 309035773 ...
 Lecture série 412/736 : ID 309035772 ...
 Lecture série 413/736 : ID 309035771 ...
 Lecture série 414/736 : ID 308606351 ...
 Lecture série 415/736 : ID 308606350 ...
 Lecture série 416/736 : ID 308605982 ...
 Lecture série 417/736 : ID 308605981 ...
 Lecture série 418/736 : ID 308605980 ...
 Lecture série 419/736 : ID 308605979 ...
 Lecture série 420/736 : ID 308484409 ...
 Lecture série 421/736 : ID 308484408 ...
 Lecture série 422/736 : ID 308484407 ...
 Lecture série 423/736 : ID 308484406 ...
 Lecture série 424/736 : ID 307225648 ...
 Lecture série 425/736 : ID 307225646 ...
 Lecture série 426/736 : ID 308128554 ...
 Lecture série 427/736 : ID 308128553 ...
 Lecture série 428/736 : ID 308128552 ...
 Lecture série 429/736 : ID 308128551 ...
 Lecture série 430/736 : ID 308128550 ...
 Lecture série 431/736 : ID 308128549 ...
 Lecture série 432/736 : ID 308128545 ...
 Lecture série 433/736 : ID 308128544 ...
 Lecture série 434/736 : ID 308128543 ...
 Lecture série 435/736 : ID 307022018 ...
 Lecture série 436/736 : ID 307022017 ...
 Lecture série 437/736 : ID 307022016 ...
 Lecture série 438/736 : ID 307022015 ...
 Lecture série 439/736 : ID 307022014 ...
 Lecture série 440/736 : ID 307022013 ...
 Lecture série 441/736 : ID 307022012 ...
 Lecture série 442/736 : ID 307022011 ...
 Lecture série 443/736 : ID 305751580 ...
 Lecture série 444/736 : ID 307527543 ...
 Lecture série 445/736 : ID 307527540 ...
 Lecture série 446/736 : ID 307527537 ...
 Lecture série 447/736 : ID 307527534 ...
 Lecture série 448/736 : ID 307527531 ...
 Lecture série 449/736 : ID 306671175 ...
 Lecture série 450/736 : ID 306671174 ...
 Lecture série 451/736 : ID 306671173 ...
 Lecture série 452/736 : ID 306900295 ...
 Lecture série 453/736 : ID 306900294 ...
 Lecture série 454/736 : ID 306900293 ...
 Lecture série 455/736 : ID 306900292 ...
 Lecture série 456/736 : ID 306900291 ...
 Lecture série 457/736 : ID 306372794 ...
 Lecture série 458/736 : ID 306372793 ...
 Lecture série 459/736 : ID 305929928 ...
 Lecture série 460/736 : ID 305929927 ...
 Lecture série 461/736 : ID 305929926 ...
 Lecture série 462/736 : ID 305929925 ...
 Lecture série 463/736 : ID 305929924 ...
 Lecture série 464/736 : ID 305929923 ...
 Lecture série 465/736 : ID 305929922 ...
 Lecture série 466/736 : ID 305929921 ...
 Lecture série 467/736 : ID 305929920 ...
 Lecture série 468/736 : ID 305929919 ...
 Lecture série 469/736 : ID 305929918 ...
 Lecture série 470/736 : ID 305929917 ...
 Lecture série 471/736 : ID 305929916 ...
 Lecture série 472/736 : ID 305929915 ...
 Lecture série 473/736 : ID 305929914 ...
 Lecture série 474/736 : ID 305929913 ...
 Lecture série 475/736 : ID 305929912 ...
 Lecture série 476/736 : ID 305929911 ...
 Lecture série 477/736 : ID 305929910 ...

In [14]:
AR_chIPseq = pd.read_csv("GEO_AR_ChIPseq_results.csv")
AR_chIPseq = AR_chIPseq.drop("Platform", axis=1)

In [15]:
AR_chIPseq

            GSE                                              Title  Samples
0     GSE315393  Recurrent FOXA1 mutation redirects NIPBL chrom...       12
1     GSE329198  PGC-1alpha pathway dysregulation disrupts myof...       14
2     GSE305396  PGC-1alpha pathway dysregulation disrupts myof...        6
3     GSE305395  PGC-1alpha pathway dysregulation disrupts myof...       27
4     GSE305394  PGC-1alpha pathway dysregulation disrupts myof...        3
..          ...                                                ...      ...
731  GSM1003798  Stanford_ChipSeq_MEL_ZNF-MIZD-CP1_(ab65767)_Ig...        0
732  GSM1003793  Stanford_ChipSeq_CH12_ZNF-MIZD-CP1_(ab65767)_I...        0
733  GSM1003611  Stanford_ChipSeq_K562_ZNF-MIZD-CP1_(ab65767)_I...        0
734   GSM712805                     AR ChIP-seq, 16h DHT treatment        0
735   GSM712804                      AR ChIP-seq, 4h DHT treatment        0

[736 rows x 3 columns]

In [16]:
AR_chIPseq.shape

(736, 3)

In [17]:
AR_chIPseq.isnull()

       GSE  Title  Samples
0    False  False    False
1    False  False    False
2    False  False    False
3    False  False    False
4    False  False    False
..     ...    ...      ...
731  False  False    False
732  False  False    False
733  False  False    False
734  False  False    False
735  False  False    False

[736 rows x 3 columns]

In [18]:
AR_chIPseq.isna()

       GSE  Title  Samples
0    False  False    False
1    False  False    False
2    False  False    False
3    False  False    False
4    False  False    False
..     ...    ...      ...
731  False  False    False
732  False  False    False
733  False  False    False
734  False  False    False
735  False  False    False

[736 rows x 3 columns]

# Extraction des séries GEO liées à CDH2 et aux expériences ChIP-seq

Ce second script reprend la même démarche que le précédent : il interroge les bases GEO du NCBI via les API ENTREZ, mais cette fois en recherchant les séries ChIP-seq associées au gène CDH2.

In [19]:
import requests               # Pour envoyer des requêtes HTTP vers les API NCBI
from bs4 import BeautifulSoup # Pour analyser les réponses XML d'ENTREZ
import pandas as pd           # Pour construire et sauvegarder le tableau final
import time                   # Pour respecter le délai entre les requêtes NCBI

# Paramètres : termes de recherche + email obligatoire pour ENTREZ

TERM = "ChIP-seq AND CDH2"  # Mot-clé de recherche sur GEO (CDH2 ChIP-seq)
EMAIL = "your_email@example.com"         # Peut rester comme ça, c'est accepté par NCBI

# URL de base pour toutes les API ENTREZ
API = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"


#  Fonction : recherche des séries GEO correspondant au terme donné

def entrez_search(term):
    """
    Recherche dans la base GEO (GDS) toutes les séries liées au terme demandé.
    Retourne une liste d'identifiants internes GDS.
    """

    url = API + "esearch.fcgi"  # API "esearch" pour interroger la base de données
    params = {
        "db": "gds",            # Base GEO DataSets
        "term": term,           # Terme de recherche
        "retmax": 5000,         # Nombre max d'entrées à renvoyer
        "retmode": "xml",       # Format de retour
        "email": EMAIL          # Email exigé par NCBI (mais pas vérifié)
    }

    r = requests.get(url, params=params)      # Envoi de la requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Analyse XML de la réponse

    # On extrait toutes les balises <Id> (identifiants internes GEO)
    ids = [id_tag.text for id_tag in soup.find_all("Id")]

    return ids  # Liste d'identifiants GDS bruts


# Fonction : récupération des informations détaillées d’un GSE

def fetch_gse_metadata(gds_id):
    """
    Récupère les métadonnées d'une série GEO via l'API esummary.
    Retourne un dictionnaire {GSE, Title, Platform, Samples}.
    Ignore les entrées incomplètes.
    """

    url = API + "esummary.fcgi"  # API "esummary" pour récupérer les infos détaillées
    params = {
        "db": "gds",             # Même base : GEO DataSets
        "id": gds_id,            # Identifiant GDS trouvé dans esearch
        "retmode": "xml",
        "email": EMAIL
    }

    r = requests.get(url, params=params)      # Requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Parsing XML

    item = soup.find("DocSum")                # Bloc principal des infos
    if item is None:
        return None  # Si vide → entrée invalidée

    # Petite fonction interne qui vérifie qu’un champ existe avant de l’extraire
    def safe_find(name):
        tag = item.find("Item", {"Name": name})
        return tag.text if tag else None

    # Extraction de l'identifiant GSE réel (ex: "GSE12345")
    acc = safe_find("Accession")
    if acc is None:
        return None  # Entrée corrompue → on ignore

    # Retour d’un dictionnaire structuré (sera ajouté au CSV)
    return {
        "GSE": acc,                     # Accession GSE
        "Title": safe_find("title"),    # Titre de l'étude
        "Platform": safe_find("platform"),  # Technologie (ex: Illumina)
        "Samples": safe_find("n_samples")   # Nombre d’échantillons
    }

# Programme principal : recherche + récupération + export CS

print("Recherche des séries via ENTREZ...")
ids = entrez_search(TERM)  # On lance la recherche de tous les GDS pertinents
print(f" {len(ids)} séries trouvées via ENTREZ.\n")

results = []  # Liste pour stocker les séries valides

# Boucle sur toutes les séries trouvées
for i, gds_id in enumerate(ids):
    print(f" Lecture série {i+1}/{len(ids)} : ID {gds_id} ...")

    data = fetch_gse_metadata(gds_id)  # Récupération des métadonnées
    if data is None:
        print("  Série ignorée (métadonnées incomplètes)")  # Problème → on saute
        continue

    results.append(data)  # Ajout à la liste des résultats valides

    time.sleep(0.34)  # Pause obligatoire pour respecter la limite NCBI (3 requêtes/sec)

# Export des résultat
print("\n----------------------------------")
print(f" Séries valides : {len(results)}")
print("----------------------------------")

df = pd.DataFrame(results)                      # Conversion en tableau pandas
df.to_csv("GEO_CDH2_ChIPseq_results.csv", index=False)  # Sauvegarde en CSV

print("Extraction terminée.")
print("Résultats enregistrés dans : GEO_CDH2_ChIPseq_results.csv")

Recherche des séries via ENTREZ...
 5 séries trouvées via ENTREZ.

 Lecture série 1/5 : ID 200267053 ...
 Lecture série 2/5 : ID 200266928 ...
 Lecture série 3/5 : ID 200239415 ...
 Lecture série 4/5 : ID 200239414 ...
 Lecture série 5/5 : ID 200113279 ...

----------------------------------
📊 Séries valides : 5
----------------------------------
Extraction terminée.
Résultats enregistrés dans : GEO_CDH2_ChIPseq_results.csv

In [20]:
CDH2_chIPseq = pd.read_csv("GEO_CDH2_ChIPseq_results.csv")
CDH2_chIPseq = CDH2_chIPseq.drop("Platform", axis=1)

In [21]:
CDH2_chIPseq

         GSE                                              Title  Samples
0  GSE267053  Rescuing DNMT1 Fails to Fully Reverse the Mole...       96
1  GSE266928  Rescuing DNMT1 Fails to Fully Reverse the Mole...       48
2  GSE239415  SAMD1 suppresses epithelial-mesenchymal transi...        6
3  GSE239414  SAMD1 suppresses epithelial-mesenchymal transi...        6
4  GSE113279  WDR5 regulates EMT and metastasis in breast ca...        5

In [22]:
CDH2_chIPseq.shape

(5, 3)

In [23]:
CDH2_chIPseq.isna()

     GSE  Title  Samples
0  False  False    False
1  False  False    False
2  False  False    False
3  False  False    False
4  False  False    False

In [24]:
CDH2_chIPseq.isna()

     GSE  Title  Samples
0  False  False    False
1  False  False    False
2  False  False    False
3  False  False    False
4  False  False    False

# Extraction des séries GEO liées à N_cadhérine et aux expériences ChIP-seq

Ce script suit la même démarche que les précédents : il interroge GEO via les API ENTREZ du NCBI, mais cette fois en recherchant les séries ChIP-seq associées à N-cadherin.

In [25]:
import requests               # Pour envoyer des requêtes HTTP vers les API NCBI
from bs4 import BeautifulSoup # Pour analyser les réponses XML d'ENTREZ
import pandas as pd           # Pour construire et sauvegarder le tableau final
import time                   # Pour respecter le délai entre les requêtes NCBI

# Paramètres : termes de recherche + email obligatoire pour ENTREZ

TERM = "ChIP-seq AND N_cadherin"  # Mot-clé de recherche sur GEO (AR ChIP-seq)
EMAIL = "your_email@example.com"         # Peut rester comme ça, c'est accepté par NCBI

# URL de base pour toutes les API ENTREZ
API = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"


#  Fonction : recherche des séries GEO correspondant au terme donné

def entrez_search(term):
    """
    Recherche dans la base GEO (GDS) toutes les séries liées au terme demandé.
    Retourne une liste d'identifiants internes GDS.
    """

    url = API + "esearch.fcgi"  # API "esearch" pour interroger la base de données
    params = {
        "db": "gds",            # Base GEO DataSets
        "term": term,           # Terme de recherche
        "retmax": 5000,         # Nombre max d'entrées à renvoyer
        "retmode": "xml",       # Format de retour
        "email": EMAIL          # Email exigé par NCBI (mais pas vérifié)
    }

    r = requests.get(url, params=params)      # Envoi de la requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Analyse XML de la réponse

    # On extrait toutes les balises <Id> (identifiants internes GEO)
    ids = [id_tag.text for id_tag in soup.find_all("Id")]

    return ids  # Liste d'identifiants GDS bruts


# Fonction : récupération des informations détaillées d’un GSE

def fetch_gse_metadata(gds_id):
    """
    Récupère les métadonnées d'une série GEO via l'API esummary.
    Retourne un dictionnaire {GSE, Title, Platform, Samples}.
    Ignore les entrées incomplètes.
    """

    url = API + "esummary.fcgi"  # API "esummary" pour récupérer les infos détaillées
    params = {
        "db": "gds",             # Même base : GEO DataSets
        "id": gds_id,            # Identifiant GDS trouvé dans esearch
        "retmode": "xml",
        "email": EMAIL
    }

    r = requests.get(url, params=params)      # Requête HTTP
    soup = BeautifulSoup(r.text, "xml")       # Parsing XML

    item = soup.find("DocSum")                # Bloc principal des infos
    if item is None:
        return None  # Si vide → entrée invalidée

    # Petite fonction interne qui vérifie qu’un champ existe avant de l’extraire
    def safe_find(name):
        tag = item.find("Item", {"Name": name})
        return tag.text if tag else None

    # Extraction de l'identifiant GSE réel (ex: "GSE12345")
    acc = safe_find("Accession")
    if acc is None:
        return None  # Entrée corrompue → on ignore

    # Retour d’un dictionnaire structuré (sera ajouté au CSV)
    return {
        "GSE": acc,                     # Accession GSE
        "Title": safe_find("title"),    # Titre de l'étude
        "Platform": safe_find("platform"),  # Technologie (ex: Illumina)
        "Samples": safe_find("n_samples")   # Nombre d’échantillons
    }

# Programme principal : recherche + récupération + export CS

print("Recherche des séries via ENTREZ...")
ids = entrez_search(TERM)  # On lance la recherche de tous les GDS pertinents
print(f" {len(ids)} séries trouvées via ENTREZ.\n")

results = []  # Liste pour stocker les séries valides

# Boucle sur toutes les séries trouvées
for i, gds_id in enumerate(ids):
    print(f" Lecture série {i+1}/{len(ids)} : ID {gds_id} ...")

    data = fetch_gse_metadata(gds_id)  # Récupération des métadonnées
    if data is None:
        print("  Série ignorée (métadonnées incomplètes)")  # Problème → on saute
        continue

    results.append(data)  # Ajout à la liste des résultats valides

    time.sleep(0.34)  # Pause obligatoire pour respecter la limite NCBI (3 requêtes/sec)

# Export des résultat
print("\n----------------------------------")
print(f" Séries valides : {len(results)}")
print("----------------------------------")

df = pd.DataFrame(results)                      # Conversion en tableau pandas
df.to_csv("GEO_N_cadherin_ChIPseq_results.csv", index=False)  # Sauvegarde en CSV
print("Extraction terminée.")
print("Résultats enregistrés dans : GEO_N_cadherin_ChIPseq_results.csv")

Recherche des séries via ENTREZ...
 68 séries trouvées via ENTREZ.

 Lecture série 1/68 : ID 200308417 ...
 Lecture série 2/68 : ID 200308183 ...
 Lecture série 3/68 : ID 200286440 ...
 Lecture série 4/68 : ID 200237500 ...
 Lecture série 5/68 : ID 200248092 ...
 Lecture série 6/68 : ID 200231753 ...
 Lecture série 7/68 : ID 200239415 ...
 Lecture série 8/68 : ID 200239414 ...
 Lecture série 9/68 : ID 200242918 ...
 Lecture série 10/68 : ID 200227823 ...
 Lecture série 11/68 : ID 200223531 ...
 Lecture série 12/68 : ID 200210523 ...
 Lecture série 13/68 : ID 200215991 ...
 Lecture série 14/68 : ID 200183407 ...
 Lecture série 15/68 : ID 200152365 ...
 Lecture série 16/68 : ID 200152364 ...
 Lecture série 17/68 : ID 200152363 ...
 Lecture série 18/68 : ID 200152362 ...
 Lecture série 19/68 : ID 200193165 ...
 Lecture série 20/68 : ID 200184856 ...
 Lecture série 21/68 : ID 200154277 ...
 Lecture série 22/68 : ID 200185682 ...
 Lecture série 23/68 : ID 200126897 ...
 Lecture série 24/68 : ID 200143148 ...
 Lecture série 25/68 : ID 200124406 ...
 Lecture série 26/68 : ID 200133072 ...
 Lecture série 27/68 : ID 200118406 ...
 Lecture série 28/68 : ID 200080218 ...
 Lecture série 29/68 : ID 200122847 ...
 Lecture série 30/68 : ID 200112555 ...
 Lecture série 31/68 : ID 200085987 ...
 Lecture série 32/68 : ID 200109545 ...
 Lecture série 33/68 : ID 200109576 ...
 Lecture série 34/68 : ID 200089418 ...
 Lecture série 35/68 : ID 200106073 ...
 Lecture série 36/68 : ID 200101064 ...
 Lecture série 37/68 : ID 200101063 ...
 Lecture série 38/68 : ID 200101062 ...
 Lecture série 39/68 : ID 200092574 ...
 Lecture série 40/68 : ID 200092347 ...
 Lecture série 41/68 : ID 200084174 ...
 Lecture série 42/68 : ID 200071018 ...
 Lecture série 43/68 : ID 200067571 ...
 Lecture série 44/68 : ID 200051334 ...
 Lecture série 45/68 : ID 200046440 ...
 Lecture série 46/68 : ID 200046166 ...
 Lecture série 47/68 : ID 200043111 ...
 Lecture série 48/68 : ID 200053025 ...
 Lecture série 49/68 : ID 200053024 ...
 Lecture série 50/68 : ID 200053023 ...
 Lecture série 51/68 : ID 200029515 ...
 Lecture série 52/68 : ID 200029514 ...
 Lecture série 53/68 : ID 200032465 ...
 Lecture série 54/68 : ID 200031477 ...
 Lecture série 55/68 : ID 305556937 ...
 Lecture série 56/68 : ID 305556936 ...
 Lecture série 57/68 : ID 305556935 ...
 Lecture série 58/68 : ID 305556934 ...
 Lecture série 59/68 : ID 305556933 ...
 Lecture série 60/68 : ID 305556932 ...
 Lecture série 61/68 : ID 303072978 ...
 Lecture série 62/68 : ID 303072977 ...
 Lecture série 63/68 : ID 302698834 ...
 Lecture série 64/68 : ID 302698833 ...
 Lecture série 65/68 : ID 301010729 ...
 Lecture série 66/68 : ID 300730632 ...
 Lecture série 67/68 : ID 300730631 ...
 Lecture série 68/68 : ID 300730630 ...

----------------------------------
 Séries valides : 68
----------------------------------
Extraction terminée.
Résultats enregistrés dans : GEO_N_cadherin_ChIPseq_results.csv

In [26]:
N_cadherin_chIPseq = pd.read_csv("GEO_N_cadherin_ChIPseq_results.csv")
N_cadherin_chIPseq = N_cadherin_chIPseq.drop("Platform", axis=1)

In [27]:
N_cadherin_chIPseq

           GSE                                              Title  Samples
0    GSE308417  Fat cadherin cleavage releases a transcription...       34
1    GSE308183  Fat cadherin cleavage releases a transcription...        6
2    GSE286440  Endothelial KLF15/VASN axis inhibits angiogene...        6
3    GSE237500  E-cadherin regulates female tumor aggressivene...       13
4    GSE248092  Tubular Foxp2 promotes kidney fibrosis by regu...        2
..         ...                                                ...      ...
63  GSM2698833                                    HIF-1a ChIP-seq        0
64  GSM1010729  HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...        0
65   GSM730632                Runx1+/VE-cadherin-/CD41+, ChIP-seq        0
66   GSM730631                Runx1+/VE-cadherin+/CD41-, ChIP-seq        0
67   GSM730630                Runx1+/VE-cadherin+/CD41+, ChIP-seq        0

[68 rows x 3 columns]

# Identification et extraction des données en commun entre AR_chIPseq et N_cadherin_chIPseq

Ces codes identifient les séries GEO communes entre les jeux de données AR ChIP-seq et N-cadherin ChIP-seq en comparant leurs identifiants GSE, puis extrait uniquement les entrées partagées pour constituer un tableau final des séries présentes dans les deux analyses.

In [28]:
matches = N_cadherin_chIPseq['GSE'].isin(AR_chIPseq['GSE'])
matches

0     False
1     False
2     False
3     False
4     False
      ...
63    False
64    False
65    False
66    False
67    False
Name: GSE, Length: 68, dtype: bool

In [30]:
AR_N_cadherin_chIPseq = AR_chIPseq[AR_chIPseq["GSE"].isin(N_cadherin_chIPseq["GSE"])]
#AR_N_cadherin_chIPseq = AR_N_cadherin_chIPseq.drop("Platform", axis=1)
AR_N_cadherin_chIPseq

          GSE                                              Title  Samples
297  GSE92574  Mapping of DHT-responsive or -independent AR-b...       16
298  GSE92347  Mapping of DHT-responsive or -independent AR-b...        9
342  GSE51334  DNA replication-timing boundaries separate sta...      993
389  GSE32465  Transcription Factor Binding Sites by ChIP-seq...      399
393  GSE31477  ENCODE Transcription Factor Binding Sites by C...      426

# Identification et extraction des données en commun entre CDH2_chIPseq et N_cadherin_chIPseq

Ces codes permettent également d’identifier les séries GEO communes entre les jeux de données CDH2 ChIP-seq et N-cadherin ChIP-seq en comparant leurs identifiants GSE, puis d’extraire uniquement les entrées partagées pour obtenir le tableau final des séries présentes dans les deux analyses.

In [31]:
matches = CDH2_chIPseq['GSE'].isin(N_cadherin_chIPseq['GSE'])
matches

0    False
1    False
2     True
3     True
4    False
Name: GSE, dtype: bool

In [32]:
CDH2_N_cadherin_chIPseq = CDH2_chIPseq[CDH2_chIPseq["GSE"].isin(N_cadherin_chIPseq["GSE"])]
CDH2_N_cadherin_chIPseq

         GSE                                              Title  Samples
2  GSE239415  SAMD1 suppresses epithelial-mesenchymal transi...        6
3  GSE239414  SAMD1 suppresses epithelial-mesenchymal transi...        6

# Identification et extraction des données en commun entre CDH2_chIPseq et AR_chIPseq

Ce code crée une série booléenne matches indiquant, pour chaque GSE de CDH2 ChIP-seq, si elle est également présente dans AR ChIP-seq. Les valeurs True correspondent aux séries communes, et False aux séries uniques à CDH2 ChIP-seq.

In [33]:
matches= CDH2_chIPseq['GSE'].isin(AR_chIPseq['GSE'])
matches

0    False
1    False
2    False
3    False
4    False
Name: GSE, dtype: bool

# Fusion des jeux de données ChIP-seq et suppression des doublons

Ce code combine les trois jeux de données (AR ChIP-seq, CDH2 ChIP-seq, N-cadherin ChIP-seq) en un seul tableau DF_commune, supprime la colonne Platform et élimine les doublons afin d’obtenir une liste unique de toutes les séries GEO présentes dans au moins un des trois jeux.

In [35]:
DF_commune = pd.concat([AR_chIPseq, CDH2_chIPseq , N_cadherin_chIPseq ], axis=0)
#DF_commune = DF_commune.drop(columns="Platform") 
DF_commune = DF_commune.drop_duplicates()

In [36]:
DF_commune

           GSE                                              Title  Samples
0    GSE315393  Recurrent FOXA1 mutation redirects NIPBL chrom...       12
1    GSE329198  PGC-1alpha pathway dysregulation disrupts myof...       14
2    GSE305396  PGC-1alpha pathway dysregulation disrupts myof...        6
3    GSE305395  PGC-1alpha pathway dysregulation disrupts myof...       27
4    GSE305394  PGC-1alpha pathway dysregulation disrupts myof...        3
..         ...                                                ...      ...
63  GSM2698833                                    HIF-1a ChIP-seq        0
64  GSM1010729  HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...        0
65   GSM730632                Runx1+/VE-cadherin-/CD41+, ChIP-seq        0
66   GSM730631                Runx1+/VE-cadherin+/CD41-, ChIP-seq        0
67   GSM730630                Runx1+/VE-cadherin+/CD41+, ChIP-seq        0

[802 rows x 3 columns]

# Ajout des liens directs vers GEO

Ce code crée une nouvelle colonne link dans DF_commune en générant pour chaque GSE un lien direct vers sa page GEO sur NCBI, facilitant la consultation rapide des séries depuis le tableau final.

In [37]:
DF_commune['link'] = DF_commune['GSE'].apply(
    lambda x: f"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc={x}"
)
DF_commune

,GSE,Title,Samples,link
0,GSE315393,Recurrent FOXA1 mutation redirects NIPBL chrom...,12,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
1,GSE329198,PGC-1alpha pathway dysregulation disrupts myof...,14,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
2,GSE305396,PGC-1alpha pathway dysregulation disrupts myof...,6,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
3,GSE305395,PGC-1alpha pathway dysregulation disrupts myof...,27,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
4,GSE305394,PGC-1alpha pathway dysregulation disrupts myof...,3,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
...,...,...,...,...
63,GSM2698833,HIF-1a ChIP-seq,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
64,GSM1010729,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
65,GSM730632,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
66,GSM730631,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
67,GSM730630,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...

In [38]:
DF_commune.to_csv('Ready_for_now.csv', index=False)

In [39]:
DF_commune = pd.read_csv("Ready_for_now.csv")
DF_commune

,GSE,Title,Samples,link
0,GSE315393,Recurrent FOXA1 mutation redirects NIPBL chrom...,12,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
1,GSE329198,PGC-1alpha pathway dysregulation disrupts myof...,14,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
2,GSE305396,PGC-1alpha pathway dysregulation disrupts myof...,6,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
3,GSE305395,PGC-1alpha pathway dysregulation disrupts myof...,27,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
4,GSE305394,PGC-1alpha pathway dysregulation disrupts myof...,3,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
...,...,...,...,...
797,GSM2698833,HIF-1a ChIP-seq,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
798,GSM1010729,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
799,GSM730632,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
800,GSM730631,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...
801,GSM730630,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...

In [40]:
from Bio import Entrez
import time

# Always provide your email to NCBI
Entrez.email = "d.ivanova@example.com"  # replace with your real email

# Load your dataframe
df = DF_commune

abstracts = []
dates = []

for i, gse_id in enumerate(DF_commune["GSE"]):
    print(f"Processing {i+1}/{len(DF_commune)}: {gse_id}")
    try:
        # Step 1: Search PubMed for the GSE ID
        search_handle = Entrez.esearch(db="pubmed", term=f"{gse_id}[All Fields]")
        search_results = Entrez.read(search_handle)
        search_handle.close()

        pmids = search_results["IdList"]

        if pmids:
            # Step 2: Fetch the first result
            fetch_handle = Entrez.efetch(db="pubmed", id=pmids[0], rettype="xml", retmode="xml")
            record = Entrez.read(fetch_handle)
            fetch_handle.close()

            article = record["PubmedArticle"][0]["MedlineCitation"]["Article"]

            # Get abstract
            abstract = article.get("Abstract", {}).get("AbstractText", ["N/A"])
            abstract_text = " ".join([str(a) for a in abstract])

            # Get date
            pub_date = article.get("Journal", {}).get("JournalIssue", {}).get("PubDate", {})
            date_str = f"{pub_date.get('Year', '')} {pub_date.get('Month', '')} {pub_date.get('Day', '')}".strip()

        else:
            abstract_text = "Not found"
            date_str = "Not found"

    except Exception as e:
        abstract_text = f"Error: {e}"
        date_str = "Error"

    abstracts.append(abstract_text)
    dates.append(date_str)

    time.sleep(0.4)  # Be polite to NCBI servers

# Add results to dataframe
df["Abstract"] = abstracts
df["Publication_Date"] = dates

# Save
df.to_excel("PUB_MED_abstracts.xlsx", index=False)
print("Done! Saved to Ready_for_now_with_abstracts.xlsx")

Processing 1/802: GSE315393
Processing 2/802: GSE329198
Processing 3/802: GSE305396
Processing 4/802: GSE305395
Processing 5/802: GSE305394
Processing 6/802: GSE305225
Processing 7/802: GSE296178
Processing 8/802: GSE289313
Processing 9/802: GSE315959
Processing 10/802: GSE241255
Processing 11/802: GSE301368
Processing 12/802: GSE301366
Processing 13/802: GSE261412
Processing 14/802: GSE318340
Processing 15/802: GSE227688
Processing 16/802: GSE306114
Processing 17/802: GSE292273

KeyboardInterrupt:

In [41]:
import pandas as pd
from Bio import Entrez
import time

Entrez.email = "d.ivanova@example.com"  # replace with your real email

abstracts = []
dates = []

def fetch_pubmed(term):
    """Search PubMed with a given term, return abstract and date or None"""
    search_handle = Entrez.esearch(db="pubmed", term=term)
    search_results = Entrez.read(search_handle)
    search_handle.close()
    
    pmids = search_results["IdList"]
    
    if pmids:
        fetch_handle = Entrez.efetch(db="pubmed", id=pmids[0], rettype="xml", retmode="xml")
        record = Entrez.read(fetch_handle)
        fetch_handle.close()
        
        article = record["PubmedArticle"][0]["MedlineCitation"]["Article"]
        
        abstract = article.get("Abstract", {}).get("AbstractText", ["N/A"])
        abstract_text = " ".join([str(a) for a in abstract])
        
        pub_date = article.get("Journal", {}).get("JournalIssue", {}).get("PubDate", {})
        date_str = f"{pub_date.get('Year', '')} {pub_date.get('Month', '')} {pub_date.get('Day', '')}".strip()
        
        return abstract_text, date_str
    
    return None, None

for i, row in enumerate(DF_commune.itertuples()):
    print(f"Processing {i+1}/{len(DF_commune)}: {row.GSE}")
    
    try:
        # Try 1: search by GSE ID
        abstract_text, date_str = fetch_pubmed(f"{row.GSE}[All Fields]")
        
        # Try 2: fallback to full title
        if abstract_text is None:
            print(f"  → Not found by GSE ID, trying full title...")
            abstract_text, date_str = fetch_pubmed(row.Title)
        
        # Try 3: fallback to shortened title
        if abstract_text is None:
            print(f"  → Trying shortened title...")
            short_title = " ".join(row.Title.split()[:8])
            abstract_text, date_str = fetch_pubmed(short_title)
        
        # If still not found after all 3 tries
        if abstract_text is None:
            abstract_text = "Not found"
            date_str = "Not found"
            print(f"  → Not found by any method")
        else:
            print(f"  → Found!")

    except Exception as e:
        abstract_text = f"Error: {e}"
        date_str = "Error"
        print(f"  → Error: {e}")

    abstracts.append(abstract_text)
    dates.append(date_str)
    time.sleep(0.4)

DF_commune["Abstract"] = abstracts
DF_commune["Publication_Date"] = dates

DF_commune.to_excel("Ready_for_now_with_abstracts.xlsx", index=False)
print("Done!")

Processing 1/802: GSE315393
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 2/802: GSE329198
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 3/802: GSE305396
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 4/802: GSE305395
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 5/802: GSE305394
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 6/802: GSE305225
  → Not found by GSE ID, trying full title...
  → Found!
Processing 7/802: GSE296178
  → Not found by GSE ID, trying full title...
  → Found!
Processing 8/802: GSE289313
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 9/802: GSE315959
  → Not found by GSE ID, trying full title...
  → Found!
Processing 10/802: GSE241255
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 11/802: GSE301368
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 12/802: GSE301366
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 13/802: GSE261412
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 14/802: GSE318340
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 15/802: GSE227688
  → Not found by GSE ID, trying full title...
  → Found!
Processing 16/802: GSE306114
  → Not found by GSE ID, trying full title...
  → Found!
Processing 17/802: GSE292273
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 18/802: GSE313838
  → Not found by GSE ID, trying full title...
  → Found!
Processing 19/802: GSE295408
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 20/802: GSE308945
  → Not found by GSE ID, trying full title...
  → Found!
Processing 21/802: GSE296270
  → Not found by GSE ID, trying full title...
  → Found!
Processing 22/802: GSE293202
  → Not found by GSE ID, trying full title...
  → Found!
Processing 23/802: GSE293101
  → Not found by GSE ID, trying full title...
  → Found!
Processing 24/802: GSE293089
  → Not found by GSE ID, trying full title...
  → Found!
Processing 25/802: GSE293080
  → Not found by GSE ID, trying full title...
  → Found!
Processing 26/802: GSE228743
  → Not found by GSE ID, trying full title...
  → Found!
Processing 27/802: GSE287905
  → Not found by GSE ID, trying full title...
  → Found!
Processing 28/802: GSE287902
  → Not found by GSE ID, trying full title...
  → Found!
Processing 29/802: GSE287901
  → Not found by GSE ID, trying full title...
  → Found!
Processing 30/802: GSE287918
  → Not found by GSE ID, trying full title...
  → Found!
Processing 31/802: GSE247347
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 32/802: GSE295844
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 33/802: GSE297048
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 34/802: GSE296236
  → Not found by GSE ID, trying full title...
  → Found!
Processing 35/802: GSE307813
  → Not found by GSE ID, trying full title...
  → Found!
Processing 36/802: GSE299760
  → Not found by GSE ID, trying full title...
  → Found!
Processing 37/802: GSE287088
  → Not found by GSE ID, trying full title...
  → Found!
Processing 38/802: GSE281784
  → Not found by GSE ID, trying full title...
  → Found!
Processing 39/802: GSE304127
  → Not found by GSE ID, trying full title...
  → Found!
Processing 40/802: GSE289031
  → Not found by GSE ID, trying full title...
  → Found!
Processing 41/802: GSE303171
  → Not found by GSE ID, trying full title...
  → Found!
Processing 42/802: GSE290863
  → Not found by GSE ID, trying full title...
  → Found!
Processing 43/802: GSE282406
  → Not found by GSE ID, trying full title...
  → Found!
Processing 44/802: GSE280834
  → Not found by GSE ID, trying full title...
  → Found!
Processing 45/802: GSE255132
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 46/802: GSE292612
  → Not found by GSE ID, trying full title...
  → Found!
Processing 47/802: GSE284519
  → Not found by GSE ID, trying full title...
  → Found!
Processing 48/802: GSE239270
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 49/802: GSE266213
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 50/802: GSE296569
  → Not found by GSE ID, trying full title...
  → Found!
Processing 51/802: GSE276050
  → Not found by GSE ID, trying full title...
  → Found!
Processing 52/802: GSE285790
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 53/802: GSE280803
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 54/802: GSE252883
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 55/802: GSE251978
  → Not found by GSE ID, trying full title...
  → Found!
Processing 56/802: GSE251977
  → Not found by GSE ID, trying full title...
  → Found!
Processing 57/802: GSE277606
  → Found!
Processing 58/802: GSE252897
  → Found!
Processing 59/802: GSE252841
  → Not found by GSE ID, trying full title...
  → Found!
Processing 60/802: GSE249437
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 61/802: GSE249435
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 62/802: GSE249887
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 63/802: GSE186873
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 64/802: GSE274717
  → Not found by GSE ID, trying full title...
  → Found!
Processing 65/802: GSE251895
  → Found!
Processing 66/802: GSE251894
  → Found!
Processing 67/802: GSE260726
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 68/802: GSE275777
  → Not found by GSE ID, trying full title...
  → Found!
Processing 69/802: GSE241290
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 70/802: GSE184311
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 71/802: GSE230508
  → Not found by GSE ID, trying full title...
  → Found!
Processing 72/802: GSE273342
  → Found!
Processing 73/802: GSE230507
  → Found!
Processing 74/802: GSE238113
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 75/802: GSE268252
  → Not found by GSE ID, trying full title...
  → Found!
Processing 76/802: GSE268124
  → Not found by GSE ID, trying full title...
  → Found!
Processing 77/802: GSE262744
  → Not found by GSE ID, trying full title...
  → Found!
Processing 78/802: GSE211138
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 79/802: GSE221140
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 80/802: GSE238209
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 81/802: GSE245749
  → Not found by GSE ID, trying full title...
  → Found!
Processing 82/802: GSE232553
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 83/802: GSE232552
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 84/802: GSE230600
  → Not found by GSE ID, trying full title...
  → Found!
Processing 85/802: GSE256129
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 86/802: GSE221263
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 87/802: GSE236860
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 88/802: GSE242734
  → Not found by GSE ID, trying full title...
  → Found!
Processing 89/802: GSE235956
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 90/802: GSE261446
  → Not found by GSE ID, trying full title...
  → Found!
Processing 91/802: GSE245967
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 92/802: GSE240679
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 93/802: GSE255308
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 94/802: GSE240055
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 95/802: GSE252635
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 96/802: GSE249686
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 97/802: GSE249685
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 98/802: GSE207472
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 99/802: GSE207230
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 100/802: GSE190956
  → Not found by GSE ID, trying full title...
  → Found!
Processing 101/802: GSE178254
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 102/802: GSE178253
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 103/802: GSE178248
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 104/802: GSE218204
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 105/802: GSE214754
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 106/802: GSE230741
  → Not found by GSE ID, trying full title...
  → Found!
Processing 107/802: GSE230740
  → Not found by GSE ID, trying full title...
  → Found!
Processing 108/802: GSE230529
  → Not found by GSE ID, trying full title...
  → Found!
Processing 109/802: GSE215161
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 110/802: GSE225196
  → Not found by GSE ID, trying full title...
  → Found!
Processing 111/802: GSE224687
  → Not found by GSE ID, trying full title...
  → Found!
Processing 112/802: GSE218092
  → Not found by GSE ID, trying full title...
  → Found!
Processing 113/802: GSE232690
  → Not found by GSE ID, trying full title...
  → Found!
Processing 114/802: GSE224422
  → Not found by GSE ID, trying full title...
  → Found!
Processing 115/802: GSE224421
  → Not found by GSE ID, trying full title...
  → Found!
Processing 116/802: GSE192562
  → Not found by GSE ID, trying full title...
  → Found!
Processing 117/802: GSE192555
  → Not found by GSE ID, trying full title...
  → Found!
Processing 118/802: GSE236287
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 119/802: GSE231748
  → Not found by GSE ID, trying full title...
  → Found!
Processing 120/802: GSE205980
  → Not found by GSE ID, trying full title...
  → Found!
Processing 121/802: GSE213664
  → Not found by GSE ID, trying full title...
  → Found!
Processing 122/802: GSE234134
  → Found!
Processing 123/802: GSE228895
  → Not found by GSE ID, trying full title...
  → Found!
Processing 124/802: GSE216373
  → Not found by GSE ID, trying full title...
  → Found!
Processing 125/802: GSE221613
  → Not found by GSE ID, trying full title...
  → Found!
Processing 126/802: GSE223406
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 127/802: GSE221826
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 128/802: GSE211945
  → Not found by GSE ID, trying full title...
  → Found!
Processing 129/802: GSE211944
  → Not found by GSE ID, trying full title...
  → Found!
Processing 130/802: GSE200300
  → Not found by GSE ID, trying full title...
  → Found!
Processing 131/802: GSE211639
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 132/802: GSE148954
  → Not found by GSE ID, trying full title...
  → Found!
Processing 133/802: GSE169129
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 134/802: GSE209047
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 135/802: GSE164968
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 136/802: GSE197781
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 137/802: GSE197780
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 138/802: GSE197776
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 139/802: GSE197774
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 140/802: GSE132073
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 141/802: GSE203036
  → Not found by GSE ID, trying full title...
  → Found!
Processing 142/802: GSE174109
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 143/802: GSE193073
  → Not found by GSE ID, trying full title...
  → Found!
Processing 144/802: GSE188173
  → Not found by GSE ID, trying full title...
  → Found!
Processing 145/802: GSE163220
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 146/802: GSE171511
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 147/802: GSE153583
  → Not found by GSE ID, trying full title...
  → Found!
Processing 148/802: GSE183200
  → Not found by GSE ID, trying full title...
  → Found!
Processing 149/802: GSE183198
  → Not found by GSE ID, trying full title...
  → Found!
Processing 150/802: GSE163316
  → Not found by GSE ID, trying full title...
  → Found!
Processing 151/802: GSE163145
  → Not found by GSE ID, trying full title...
  → Found!
Processing 152/802: GSE163143
  → Not found by GSE ID, trying full title...
  → Found!
Processing 153/802: GSE198916
  → Found!
Processing 154/802: GSE179684
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 155/802: GSE188150
  → Not found by GSE ID, trying full title...
  → Found!
Processing 156/802: GSE153661
  → Not found by GSE ID, trying full title...
  → Found!
Processing 157/802: GSE162293
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 158/802: GSE157862
  → Not found by GSE ID, trying full title...
  → Found!
Processing 159/802: GSE181224
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 160/802: GSE157107
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 161/802: GSE157104
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 162/802: GSE171592
  → Not found by GSE ID, trying full title...
  → Found!
Processing 163/802: GSE171589
  → Not found by GSE ID, trying full title...
  → Found!
Processing 164/802: GSE148807
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 165/802: GSE145333
  → Not found by GSE ID, trying full title...
  → Found!
Processing 166/802: GSE145196
  → Not found by GSE ID, trying full title...
  → Found!
Processing 167/802: GSE169073
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 168/802: GSE138460
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 169/802: GSE147875
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 170/802: GSE136016
  → Not found by GSE ID, trying full title...
  → Found!
Processing 171/802: GSE158279
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 172/802: GSE155803
  → Not found by GSE ID, trying full title...
  → Found!
Processing 173/802: GSE146886
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 174/802: GSE154191
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 175/802: GSE148935
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 176/802: GSE168651
  → Not found by GSE ID, trying full title...
  → Found!
Processing 177/802: GSE164543
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 178/802: GSE151424
  → Not found by GSE ID, trying full title...
  → Found!
Processing 179/802: GSE171005
  → Found!
Processing 180/802: GSE147939
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 181/802: GSE147938
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Found!
Processing 182/802: GSE151619
  → Not found by GSE ID, trying full title...
  → Found!
Processing 183/802: GSE161189
  → Not found by GSE ID, trying full title...
  → Found!
Processing 184/802: GSE166192
  → Not found by GSE ID, trying full title...
  → Found!
Processing 185/802: GSE161167
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method
Processing 186/802: GSE156280
  → Not found by GSE ID, trying full title...
  → Found!
Processing 187/802: GSE141582
  → Not found by GSE ID, trying full title...
  → Found!
Processing 188/802: GSE141394
  → Not found by GSE ID, trying full title...
  → Found!
Processing 189/802: GSE129930
  → Not found by GSE ID, trying full title...
  → Found!
Processing 190/802: GSE129929
  → Not found by GSE ID, trying full title...
  → Found!
Processing 191/802: GSE123767
  → Not found by GSE ID, trying full title...
  → Found!
Processing 192/802: GSE123764
  → Not found by GSE ID, trying full title...
  → Found!
Processing 193/802: GSE163623
  → Not found by GSE ID, trying full title...
  → Found!
Processing 194/802: GSE162319
  → Not found by GSE ID, trying full title...
  → Found!
Processing 195/802: GSE144960
  → Not found by GSE ID, trying full title...
  → Found!
Processing 196/802: GSE149439
  → Not found by GSE ID, trying full title...
  → Trying shortened title...
  → Not found by any method

In [46]:
not_found = (DF_commune["Abstract"]=="Not found").sum()
total = len(DF_commune)
found = total - not_found
print(f"Found:     {found}/{total}")
print(f"Not found: {not_found}/{total}")

Found:     403/802
Not found: 399/802

In [1]:
!pip install keybert

Collecting keybert
  Downloading keybert-0.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from keybert) (2.3.3)
Collecting rich>=10.4.0 (from keybert)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: scikit-learn>=0.22.2 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from keybert) (1.7.1)
Collecting sentence-transformers>=0.3.8 (from keybert)
  Downloading sentence_transformers-5.5.0-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.4.0->keybert)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from rich>=10.4.0->keybert) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: scipy>=1.8.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=0.22.2->keybert) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=0.22.2->keybert) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from scikit-learn>=0.22.2->keybert) (3.5.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert) (4.57.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert) (0.34.4)
Collecting torch>=1.11.0 (from sentence-transformers>=0.3.8->keybert)
  Downloading torch-2.12.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from sentence-transformers>=0.3.8->keybert) (4.67.1)
Requirement already satisfied: filelock in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.20.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.11.3)
Requirement already satisfied: requests in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.3.8->keybert) (2025.10.0)
Requirement already satisfied: setuptools<82 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (78.1.1)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.1.6)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.3.8->keybert)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from tqdm>=4.0.0->sentence-transformers>=0.3.8->keybert) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.3.8->keybert) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dani\miniconda3\envs\myenv\lib\site-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.3.8->keybert) (2025.8.3)
Downloading keybert-0.9.0-py3-none-any.whl (41 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading sentence_transformers-5.5.0-py3-none-any.whl (588 kB)
   ---------------------------------------- 0.0/588.7 kB ? eta -:--:--
   ---------------------------------------- 588.7/588.7 kB 6.7 MB/s  0:00:00
Downloading torch-2.12.0-cp313-cp313-win_amd64.whl (123.0 MB)
   ---------------------------------------- 0.0/123.0 MB ? eta -:--:--
   - -------------------------------------- 3.1/123.0 MB 15.1 MB/s eta 0:00:08
   - -------------------------------------- 6.0/123.0 MB 14.3 MB/s eta 0:00:09
   --- ------------------------------------ 10.5/123.0 MB 16.4 MB/s eta 0:00:07
   ---- ----------------------------------- 15.2/123.0 MB 18.0 MB/s eta 0:00:06
   ------ --------------------------------- 20.4/123.0 MB 19.4 MB/s eta 0:00:06
   -------- ------------------------------- 25.4/123.0 MB 20.2 MB/s eta 0:00:05
   ---------- ----------------------------- 31.7/123.0 MB 21.3 MB/s eta 0:00:05
   ------------ --------------------------- 38.0/123.0 MB 22.4 MB/s eta 0:00:04
   -------------- ------------------------- 43.5/123.0 MB 23.0 MB/s eta 0:00:04
   ---------------- ----------------------- 50.1/123.0 MB 23.9 MB/s eta 0:00:04
   ------------------ --------------------- 55.8/123.0 MB 24.3 MB/s eta 0:00:03
   -------------------- ------------------- 61.9/123.0 MB 24.7 MB/s eta 0:00:03
   ---------------------- ----------------- 68.4/123.0 MB 25.2 MB/s eta 0:00:03
   ------------------------ --------------- 75.2/123.0 MB 25.6 MB/s eta 0:00:02
   -------------------------- ------------- 82.3/123.0 MB 26.1 MB/s eta 0:00:02
   ---------------------------- ----------- 89.1/123.0 MB 26.5 MB/s eta 0:00:02
   ------------------------------- -------- 96.7/123.0 MB 27.0 MB/s eta 0:00:01
   -------------------------------- ------ 102.5/123.0 MB 27.1 MB/s eta 0:00:01
   ---------------------------------- ---- 109.3/123.0 MB 27.4 MB/s eta 0:00:01
   ------------------------------------ -- 115.3/123.0 MB 27.5 MB/s eta 0:00:01
   --------------------------------------  121.9/123.0 MB 27.8 MB/s eta 0:00:01
   --------------------------------------  122.9/123.0 MB 27.8 MB/s eta 0:00:01
   ---------------------------------------- 123.0/123.0 MB 26.4 MB/s  0:00:04
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 21.7 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ---------------------------------------  6.3/6.3 MB 31.6 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 26.1 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 12.1 MB/s  0:00:00
Installing collected packages: mpmath, sympy, networkx, mdurl, torch, markdown-it-py, rich, sentence-transformers, keybert

   ---------------------------------------- 0/9 [mpmath]
   ---------------------------------------- 0/9 [mpmath]
   ---------------------------------------- 0/9 [mpmath]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   ---- ----------------------------------- 1/9 [sympy]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   -------- ------------------------------- 2/9 [networkx]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ----------------- ---------------------- 4/9 [torch]
   ---------------------- ----------------- 5/9 [markdown-it-py]
   -------------------------- ------------- 6/9 [rich]
   -------------------------- ------------- 6/9 [rich]
   ------------------------------- -------- 7/9 [sentence-transformers]
   ------------------------------- -------- 7/9 [sentence-transformers]
   ------------------------------- -------- 7/9 [sentence-transformers]
   ------------------------------- -------- 7/9 [sentence-transformers]
   ---------------------------------------- 9/9 [keybert]

Successfully installed keybert-0.9.0 markdown-it-py-4.2.0 mdurl-0.1.2 mpmath-1.3.0 networkx-3.6.1 rich-15.0.0 sentence-transformers-5.5.0 sympy-1.14.0 torch-2.12.0

In [10]:
import pandas as pd
DF_commune = pd.read_csv("Ready_for_now_with_abstracts.csv", encoding="latin-1")
DF_commune

,GSE,Title,Samples,link,Abstract PUB MED,Publication_Date
0,GSE315393,Recurrent FOXA1 mutation redirects NIPBL chrom...,12,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
1,GSE329198,PGC-1alpha pathway dysregulation disrupts myof...,14,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
2,GSE305396,PGC-1alpha pathway dysregulation disrupts myof...,6,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
3,GSE305395,PGC-1alpha pathway dysregulation disrupts myof...,27,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
4,GSE305394,PGC-1alpha pathway dysregulation disrupts myof...,3,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
...,...,...,...,...,...,...
797,GSM2698833,HIF-1a ChIP-seq,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Clear cell renal cell carcinoma (ccRCC) is pri...,2026 Apr 17
798,GSM1010729,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
799,GSM730632,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
800,GSM730631,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found
801,GSM730630,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found

## Ici le code permet d'ajouter les abstraits depuis PUB MED

In [13]:
from keybert import KeyBERT

# Load the model
kw_model = KeyBERT()

def extract_keywords(abstract, n=5):
    # Skip empty/NaN/not found values
    if pd.isna(abstract):
        return []
    # Skip rows with no abstract
    if abstract in ["Not found", "N/A"] or "Error" in str(abstract):
        return []
    
    keywords = kw_model.extract_keywords(
        abstract,
        keyphrase_ngram_range=(1, 2),  # single words and 2-word phrases
        stop_words='english',           # ignore common words like "the", "and"
        top_n=n                         # number of keywords to extract
    )
    return [kw[0] for kw in keywords]  # return just the words, not the scores

# Apply to all abstracts
print("Extracting keywords...")
DF_commune["Keywords"] = DF_commune["Abstract PUB MED"].apply(extract_keywords)
print("Done!")

# Preview results
print(DF_commune[["GSE", "Keywords"]].head(10))

Extracting keywords...
Done!
         GSE                                           Keywords
0  GSE315393                                                 []
1  GSE329198                                                 []
2  GSE305396                                                 []
3  GSE305395                                                 []
4  GSE305394                                                 []
5  GSE305225  [h3k9me3 seeds, seed dormancy, seeds arabidops...
6  GSE296178  [androgen receptor, prostate lineage, hormonal...
7  GSE289313  [pathogenesis psoriasis, kynureninase psoriasi...
8  GSE315959  [foxa1 binding, foxa1 pioneering, androgen rec...
9  GSE241255  [6ma chromatin, lncrna chromatin, methyltransf...

In [14]:
DF_commune

,GSE,Title,Samples,link,Abstract PUB MED,Publication_Date,Keywords
0,GSE315393,Recurrent FOXA1 mutation redirects NIPBL chrom...,12,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
1,GSE329198,PGC-1alpha pathway dysregulation disrupts myof...,14,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
2,GSE305396,PGC-1alpha pathway dysregulation disrupts myof...,6,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
3,GSE305395,PGC-1alpha pathway dysregulation disrupts myof...,27,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
4,GSE305394,PGC-1alpha pathway dysregulation disrupts myof...,3,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
...,...,...,...,...,...,...,...
797,GSM2698833,HIF-1a ChIP-seq,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Clear cell renal cell carcinoma (ccRCC) is pri...,2026 Apr 17,"[micrornas implicated, micrornas, expression m..."
798,GSM1010729,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
799,GSM730632,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
800,GSM730631,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]
801,GSM730630,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",0,https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi...,Not found,Not found,[]

In [16]:
DF_commune2 = pd.read_csv("GEO_GSE_summary_corrected.csv", encoding="latin-1")
DF_commune2

,GSE,Samples,Title,Design_GSE,Summary_GSE,Title_GSE
0,GSE315959,51,Dissecting FOXA1 pioneering function by acute ...,NaN,Pioneer factors control transcription by openi...,Dissecting FOXA1 pioneering function by acute ...
1,GSE241255,4,Chromatin immunoprecipitation DNA sequencing (...,NaN,Purpose: Zinc Finger MIZ-Type Containing 1 (Zm...,Chromatin immunoprecipitation DNA sequencing (...
2,GSE301368,10,Acute hormonal signaling-induced 3D chromatin ...,NaN,Recent molecular advancements have revolutioni...,Acute hormonal signaling-induced 3D chromatin ...
3,GSE301366,24,Acute hormonal signaling-induced 3D chromatin ...,NaN,Recent molecular advancements have revolutioni...,Acute hormonal signaling-induced 3D chromatin ...
4,GSE261412,24,Acute hormonal signaling-induced 3D chromatin ...,NaN,Î²3-adrenergic receptor (Î²3-AR) hormonal sign...,Acute hormonal signaling-induced 3D chromatin ...
...,...,...,...,...,...,...
786,GSM2698833,0,HIF-1a ChIP-seq,NaN,This SuperSeries is composed of the SubSeries ...,Open Chromatin and HIF-binding in renal tubula...
787,GSM1010729,0,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,NaN,Eukaryotic chromosomes replicate in a temporal...,DNA replication-timing boundaries separate sta...
788,GSM730632,0,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...
789,GSM730631,0,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...
790,GSM730630,0,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...

In [25]:
# Check column names exactly
print(DF_commune2.columns.tolist())

# Check how many are GSE vs GSM
print("GSE entries:", DF_commune2["GSE"].str.startswith("GSE").sum())
print("GSM entries:", DF_commune2["GSE"].str.startswith("GSM").sum())

# Check how many Summary_GSE are filled
print("Summaries filled:", DF_commune2["Summary_GSE"].notna().sum())

['GSE', 'Samples', 'Title', 'Design_GSE', 'Summary_GSE', 'Title_GSE']
GSE entries: 449
GSM entries: 342
Summaries filled: 791

In [26]:
from keybert import KeyBERT
import pandas as pd

kw_model = KeyBERT()

def extract_keywords(text, n=5):
    if pd.isna(text):
        return []
    if text in ["Not found", "N/A"] or "Error" in str(text):
        return []
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 2),
        stop_words='english',
        top_n=n
    )
    return [kw[0] for kw in keywords]

print("Extracting keywords...")
DF_commune2["Keywords"] = DF_commune2["Summary_GSE"].apply(extract_keywords)
print("Done!")
print(DF_commune2[["GSE", "Keywords"]].head())

Extracting keywords...
Done!
         GSE                                           Keywords
0  GSE315959  [genes foxa1, foxa1 binding, foxa1 pioneering,...
1  GSE241255  [sequencing zmiz1, zmiz1 associated, containin...
2  GSE301368  [adipocytes, brown adipocytes, receptor î²3, a...
3  GSE301366  [adipocytes, brown adipocytes, receptor î²3, a...
4  GSE261412  [adipocytes implications, 3d genome, receptor ...

In [27]:
DF_commune2

,GSE,Samples,Title,Design_GSE,Summary_GSE,Title_GSE,Keywords
0,GSE315959,51,Dissecting FOXA1 pioneering function by acute ...,NaN,Pioneer factors control transcription by openi...,Dissecting FOXA1 pioneering function by acute ...,"[genes foxa1, foxa1 binding, foxa1 pioneering,..."
1,GSE241255,4,Chromatin immunoprecipitation DNA sequencing (...,NaN,Purpose: Zinc Finger MIZ-Type Containing 1 (Zm...,Chromatin immunoprecipitation DNA sequencing (...,"[sequencing zmiz1, zmiz1 associated, containin..."
2,GSE301368,10,Acute hormonal signaling-induced 3D chromatin ...,NaN,Recent molecular advancements have revolutioni...,Acute hormonal signaling-induced 3D chromatin ...,"[adipocytes, brown adipocytes, receptor î²3, a..."
3,GSE301366,24,Acute hormonal signaling-induced 3D chromatin ...,NaN,Recent molecular advancements have revolutioni...,Acute hormonal signaling-induced 3D chromatin ...,"[adipocytes, brown adipocytes, receptor î²3, a..."
4,GSE261412,24,Acute hormonal signaling-induced 3D chromatin ...,NaN,Î²3-adrenergic receptor (Î²3-AR) hormonal sign...,Acute hormonal signaling-induced 3D chromatin ...,"[adipocytes implications, 3d genome, receptor ..."
...,...,...,...,...,...,...,...
786,GSM2698833,0,HIF-1a ChIP-seq,NaN,This SuperSeries is composed of the SubSeries ...,Open Chromatin and HIF-binding in renal tubula...,"[superseries composed, subseries listed, super..."
787,GSM1010729,0,HudsonAlpha_ChipSeq_GM12878_MTA3_(SC-81325)_v0...,NaN,Eukaryotic chromosomes replicate in a temporal...,DNA replication-timing boundaries separate sta...,"[chromosomes replicate, regions chromatin, chr..."
788,GSM730632,0,"Runx1+/VE-cadherin-/CD41+, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...,"[superseries composed, subseries listed, super..."
789,GSM730631,0,"Runx1+/VE-cadherin+/CD41-, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...,"[superseries composed, subseries listed, super..."
790,GSM730630,0,"Runx1+/VE-cadherin+/CD41+, ChIP-seq",NaN,This SuperSeries is composed of the SubSeries ...,The transcriptional program controlled by Runx...,"[superseries composed, subseries listed, super..."